### ISSUE TITLE
Ubuntu LTS?

### ISSUE THREAD

**Issue by josephwb** [bredelings/BAli-Phy#9]
It is nice that BAli-Phy is [available using package managers](http://www.bali-phy.org/download.php). However, it is not available on the current Ubuntu LTS release (v18.04).

Is it possible to make it available from an LTS (which I imagine most users, er, use), or are there significant roadblocks?

If this is not possible, it is not a big deal, as building it is straightforward (and the precompiled binaries are almost as convenient).

**Comment by bredelings** [comment]
Yeah, this is an issue.  Debian testing and Ubuntu active development (currently fossa) will get packages automatically in a few days.  But for old Ubuntu releases, I have to build packages specifically and then distribute them.  The easiest way right now is probably to download the tarball instead of using a package manager.

Making DEB packages for older ubuntu should be doable.  I am already compiling them through github actions on an older ubuntu.  Making a DEB could also be done, but I have to figure out how to do that in this context.

Then I have to upload them to a PPA, I guess.

**Comment by bredelings** [comment]
As a side comment, I personally use Debian testing for servers and Debian "unstable" for desktop/laptop.  I like the rolling releases better than the Ubuntu static release model.

**Comment by josephwb** [comment]
Understood. Thanks.

**Comment by bredelings** [comment]
I'm going to try to figure out how to run a DEB creation process from github actions.

**Comment by josephwb** [comment]
Ok, kewl. I was more curious than anything, although I imagine it will eventually be useful.
